# Generated by Django 3.1.2 on 2023-10-10 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_city_capital'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='City',
            new_name='Cidade',
        ),
    ]
