version: '3.5'

services:

  app:
    build: .
    ports:
      - "8001:8000"
    volumes:
      - .:/code
    entrypoint: ['sh', 'run-django.sh']

  sidia_bd:
    image: mdillon/postgis
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: sidia
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

volumes:
  postgres-data: